### ISSUE TITLE
weex-acechart 问题

### ISSUE THREAD

**Issue by VICTORYGS** [AntiMoron/pornhub-emoji#5]
大佬麻烦问下 weex-acechart 这个ios折线图 y轴的数字不会和安卓一样自动进行 千分位格式化显示（例如 2,127,520.32）。这应该怎么处理呢

**Comment by AntiMoron** [comment]
@VICTORYGS 现在转纯前端了也暂时不负责这个项目了。。。

不过我看起来这个应该是支持的，我记得之前文档有写：



>yAxises[i].commonFormat: String
通用的format类型，接受如下两种
>  - 'shortenNumber'   自动保留小数，并且会通过增加数字单位化简
>  - 'percentage'      百分比
